import type { Metadata } from 'next';
import './globals.css';
import * as React from 'react';
import CustomThemeProvider from '@/providers/CustomThemeProvider';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import Profile from '@/components/profile/Profile';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <CustomThemeProvider>
          <Header />
          <Profile />
          {children}
          <Footer />
        </CustomThemeProvider>
      </body>
    </html>
  );
}
